name: Atualizar RSS

on:
  schedule:
    - cron: "0 */3 * * *"  # A cada 3 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Rodar script
        run: node rss-builder.js

      - name: Commit & Push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.xml feeds.json
          git commit -m "Atualiza feed RSS" || echo "Nada para commitar"
          git push
